#137011075 Include bundling task in gulp task runner
andela/project-arakari pull request #36
Opened 2017-01-16 19:52 UTC by andela-Bgathu

#### What does this PR do?
Adds bundling task in gulp task runner
fixes the problem with the coverage badge and coveralls progress
 #### Description of Task to be completed?
Include bundling task in gulp task runner
 #### How should this be manually tested?
After installing and running `npm install` check to see if there is a ./public/bundle folder
for the coverage check this branches coverage badge it reads 44%
 #### Any background context you want to provide?
 #### What are the relevant pivotal tracker stories?
#137011075

2017-01-16 20:42 UTC, gangachris commented
This has to wait for #13

2017-01-18 07:03 UTC, jackiewmacharia approved these changes

2017-01-24 08:06 UTC, jkanyua approved these changes

2017-01-24 08:17 UTC, jkanyua requested changes

2017-01-24 08:17 UTC, andela-jkanyua commented on app/views/includes/head.pug
> +  //- link(rel='stylesheet', href='/css/common.css')
So, since we are bundling all css to a single file (main.css), we don't need the commented out code here.

2017-01-24 08:17 UTC, andela-jkanyua commented on app/views/includes/foot.pug
> +//- script(type='text/javascript', src='/js/app.js')
So, since we are bundling all js files to a single file we don't need the commented out code here.

2017-01-24 08:17 UTC, andela-jkanyua commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/andela/project-arakari/badge.svg?branch=chore%2F137011075%2FInclude-bundling-task-in-gulp-task-runner)](https://coveralls.io/github/andela/projec
Since were merging to develop, I think we should leave this to point to develop.

2017-01-24 10:56 UTC, andela-Bgathu commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/andela/project-arakari/badge.svg?branch=chore%2F137011075%2FInclude-bundling-task-in-gulp-task-runner)](https://coveralls.io/github/andela/projec
point to develop

2017-01-24 11:05 UTC, closed without merging