#135842529 search users endpoint
andela/project-arakari pull request #39
Opened 2017-01-18 16:55 UTC by andela-wmaina

#### What does this PR do?
Adds api/search/users endpoint
 #### Description of Task to be completed?
Returns all the current users
 #### How should this be manually tested?
 #### Any background context you want to provide?
It is an authenticated endpoint thus can only be accessed once you are authenticated. 
 #### What are the relevant pivotal tracker stories?
#135842529
 #### Screenshots (if appropriate)
 #### Questions:

2017-01-23 11:57 UTC, andela-Bgathu commented on app/controllers/users.js
> +  }, function(err, users) {
Add error handling in case of any.

2017-01-23 11:58 UTC, andela-Bgathu commented on config/routes.js
> +    app.get('/api/search/users', users.authToken, users.searchUsers);
work with Boswell to make sure that when there is a token, it is actually authenticated

2017-01-23 12:01 UTC, boswellgathu requested changes
Make those changes then I will review

2017-01-24 05:09 UTC, andela-wmaina commented on app/controllers/users.js
> +    if (err) return next(err);
@andela-Bgathu Thanks for the observation. I've added it.

2017-01-24 08:03 UTC, andela-kakpobome commented
### Critical

@andela-wmaina why do we have a hashed password in the response?!

2017-01-24 08:03 UTC, closed without merging