chore:(karma): add karma and jasmine to setup frontend testing
andela/project-arakari pull request #8
Opened 2016-12-21 07:10 UTC by andela-jkanyua

adds jasmine and karma with phantomJs chrome and firefox devDependencies

Delivers #135842519

 #### What does this PR do?
 It adds Karma to setup front end testing environment.

 #### Description of Task to be completed?
It adds Jasmine and Karma(with PhantomJS, Chrome and Firefox) to setup front end testing environment.

 #### How should this be manually tested?
run:
```
karma start
```
 #### Any background context you want to provide?
 #### What are the relevant pivotal tracker stories?
#135842519
 #### Screenshots (if appropriate)
 #### Questions:

2016-12-21 11:14 UTC, boswellgathu requested changes
Check on the wiki on how to create a pull request, including the heading

2016-12-24 17:43 UTC, gangachris commented
@andela-jkanyua You have conflicts.

2016-12-28 09:14 UTC, gangachris commented
@andela-jkanyua I see the smoke-test, but it has not yet been included in our continuous deployment. I think you still have to manually run Karma to run the tests. Work with @andela-cwekesa to see how to add it to the gulp tasks, or one of the npm scripts. It should also include coverage, so @andela-Bgathu has to aslo chip in.

2016-12-28 09:37 UTC, GathuBoswell approved these changes

2017-01-04 11:10 UTC, andela-jkanyua commented on karma.conf.js
> +    './test/test-spec.js',
test should be last

2017-01-05 09:10 UTC, gangachris commented
@andela-jkanyua please make the changes we talked about when you can and reopen this.

2017-01-05 09:10 UTC, closed without merging